### ISSUE TITLE
Evaluate multiple queries per cell

### ISSUE THREAD

**Issue by mewim** [kuzudb/explorer#5]
TODOs:
- [x] Fix auto-complete grammar for multiple query statements (done in #133)
- [x] Allow multiple queries to be evaluated (requires https://github.com/kuzudb/kuzu/issues/3154).
- [x] Return result of last query (requires https://github.com/kuzudb/kuzu/issues/3214).

**Comment by mewim** [comment]
This can be supported after merging https://github.com/kuzudb/kuzu/pull/2889
